
name: Run Google Sheet Analysis
on: workflow_dispatch

jobs:

  run-analysis:
    name: Run Google Sheet Analysis
    runs-on: ubuntu-latest
    container:
      # Use a container that has most dependencies installed.
      # It doesn't have to be this one
      image: jhudsl/base_ottr:latest

    steps:
      # Get files from the repository
      - name: checkout
        uses: actions/checkout@v4
        
      # Query Google Sheets API
      - name: get data
        id: get_sheet
        uses: jroehl/gsheet.action@v2.1.1
        with:
          spreadsheetId: 1QNBCCk4eIsSLw9I_KdNtWiBYEKz-mHSzLVYLYlN6c9U # Specific Google Sheet URL
          commands: | # list of commands, specified as a valid JSON string
            [
              { "command": "getWorksheet", "args": { "worksheetTitle": "Sheet1" }},
              { "command": "getData", "args": { "range": "'Sheet1'!A:B" } }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
        
      # Run the analysis
      - name: Run render script
        env:
          #  the output of the action above!
          RESULTS: ${{ steps.get_sheet.outputs.results }}
        run: |
          Rscript --vanilla "R/render.R" --data_in "$RESULTS"
          